[openssl-3] Update to OpenSSL 3.2.1. JB#55609
sailfishos/openssl pull request #7
Opened 2024-03-25 09:12 UTC by Thaodan

2024-10-20 14:38 UTC, mlehtima requested changes

2024-10-20 14:38 UTC, mlehtima commented on rpm/openssl.spec
> +%endif
This should be at the very end of the %check part just before %install

2025-02-05 14:17 UTC, pvuorela commented on rpm/openssl.spec
> +License:        Apache-2.0
ASL 2.0 by the current form we use.

2025-02-05 14:17 UTC, pvuorela commented on rpm/openssl.spec
> -%package perl
Please keep the perl subpackage. I don't want it pulled in unless really really needed.

2025-02-05 22:57 UTC, Thaodan commented on rpm/openssl.spec
> +License:        Apache-2.0
We shouldn't drop the SPDX tag.. Doing so only makes the indexing of licenses harder.

2025-02-06 07:00 UTC, pvuorela commented on rpm/openssl.spec
> +License:        Apache-2.0
We've had this conversation already.

2025-02-24 15:22 UTC, mlehtima requested changes
Some change requests, also rebase is needed.

2025-02-24 15:22 UTC, mlehtima commented on rpm/openssl.spec
> +Patch0005:      0005-Add-default-section-to-load-crypto-policies-configur.patch
Remove this patch, it breaks without crypto-policies package.

2025-02-24 15:22 UTC, mlehtima commented on rpm/openssl.spec
> +# Requires:       crypto-policies
Remove this commented out requirement for now, it can be added back if we later take crypto-policies into use, we will remove the currently broken patch also as seen in the other comment.

2025-08-05 06:24 UTC, pvuorela commented
Followup PR merged, this shouldn't be needed anymore.

2025-08-05 06:24 UTC, closed without merging